require('dotenv').config();
const { google } = require('googleapis');
const { getGoogleAuth } = require('./auth/googleAuth');

function toBase64Url(str) {
  return Buffer.from(str)
    .toString('base64')
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=/g, '');
}

function buildMimeMessage(to, from, subject, htmlBody) {
  const message = [
    `From: ${from}`,
    `To: ${to}`,
    `Subject: ${subject}`,
    'MIME-Version: 1.0',
    'Content-Type: text/html; charset=UTF-8',
    '',
    htmlBody
  ].join('\r\n');

  return toBase64Url(message);
}

function buildTrainerHtml(member, inbody, assessment, workout, nutrition) {
  const escape = (v) => String(v == null ? '' : v).replace(/</g, '&lt;').replace(/>/g, '&gt;');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  body{font-family:Arial,Helvetica,sans-serif;color:#222;max-width:900px;margin:0 auto;padding:20px;font-size:14px}
  h1{color:#1a1a2e;margin-bottom:4px}
  h2{color:#0f3460;border-bottom:3px solid #0f3460;padding-bottom:6px;margin-top:32px}
  table{width:100%;border-collapse:collapse;margin:12px 0}
  th{background:#0f3460;color:#fff;padding:10px 12px;text-align:left}
  td{border:1px solid #ddd;padding:9px 12px;vertical-align:top}
  tr:nth-child(even) td{background:#f5f7fa}
  pre{background:#f8f8f8;padding:16px;border-left:4px solid #0f3460;white-space:pre-wrap;word-wrap:break-word;font-family:Arial,Helvetica,sans-serif;font-size:13px;margin:0}
  .footer{margin-top:40px;padding:14px;background:#f0f0f0;text-align:center;font-size:12px;color:#777;border-radius:4px}
</style>
</head>
<body>
  <h1>New Member Onboarding Report</h1>
  <p style="color:#666;margin-top:0">Auto-generated by Gym Onboarding AI</p>

  <h2>Member Details</h2>
  <table>
    <tr><th>Field</th><th>Value</th></tr>
    <tr><td>Name</td><td>${escape(member.name)}</td></tr>
    <tr><td>Email</td><td>${escape(member.email)}</td></tr>
    <tr><td>Phone</td><td>${escape(member.phone)}</td></tr>
    <tr><td>Age</td><td>${escape(member.age)}</td></tr>
    <tr><td>Gender</td><td>${escape(member.gender)}</td></tr>
    <tr><td>Primary Goal</td><td>${escape(member.primary_goal)}</td></tr>
    <tr><td>Training Experience</td><td>${escape(member.training_experience)}</td></tr>
    <tr><td>Days Available Per Week</td><td>${escape(member.days_available)}</td></tr>
    <tr><td>Injury History</td><td>${escape(member.injury_history)}</td></tr>
    <tr><td>Medical Considerations</td><td>${escape(member.medical_considerations)}</td></tr>
  </table>

  <h2>InBody Metrics</h2>
  <table>
    <tr><th>Metric</th><th>Value</th></tr>
    <tr><td>Weight</td><td>${escape(inbody.weight_kg)} kg</td></tr>
    <tr><td>Skeletal Muscle Mass</td><td>${escape(inbody.skeletal_muscle_mass_kg)} kg</td></tr>
    <tr><td>Body Fat Mass</td><td>${escape(inbody.body_fat_mass_kg)} kg</td></tr>
    <tr><td>Body Fat %</td><td>${escape(inbody.body_fat_percentage)}%</td></tr>
    <tr><td>BMI</td><td>${escape(inbody.bmi)}</td></tr>
    <tr><td>BMR</td><td>${escape(inbody.bmr_kcal)} kcal/day</td></tr>
    <tr><td>Visceral Fat Level</td><td>${escape(inbody.visceral_fat_level)}</td></tr>
    <tr><td>Total Body Water</td><td>${escape(inbody.total_body_water_L)} L</td></tr>
    <tr><td>InBody Score</td><td>${escape(inbody.inbody_score)}</td></tr>
  </table>

  <h2>Trainer Assessment</h2>
  <pre>${escape(assessment)}</pre>

  <h2>Workout Plan</h2>
  <pre>${escape(workout)}</pre>

  <h2>Nutrition Plan</h2>
  <pre>${escape(nutrition)}</pre>

  <div class="footer">Auto-generated by Gym Onboarding AI</div>
</body>
</html>`;
}

function buildClientHtml(member, assessment, workout, nutrition, gymName) {
  const escape = (v) => String(v == null ? '' : v).replace(/</g, '&lt;').replace(/>/g, '&gt;');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  body{font-family:Arial,Helvetica,sans-serif;color:#222;max-width:800px;margin:0 auto;padding:20px;font-size:14px}
  h1{margin:0;color:#fff}
  h2{color:#16213e;border-bottom:3px solid #e94560;padding-bottom:6px;margin-top:32px}
  .header{background:#1a1a2e;color:#fff;padding:28px 24px;border-radius:8px;margin-bottom:24px}
  .header p{margin:8px 0 0;color:#ccc;font-size:15px}
  pre{background:#f8f8f8;padding:16px;border-left:4px solid #e94560;white-space:pre-wrap;word-wrap:break-word;font-family:Arial,Helvetica,sans-serif;font-size:13px;margin:0}
  .next-steps{background:#e8f5e9;border:1px solid #388e3c;padding:20px;border-radius:6px}
  .next-steps h2{border-color:#388e3c;color:#1b5e20}
  ol{margin:8px 0;padding-left:20px;line-height:1.9}
  .footer{margin-top:40px;padding:16px;background:#1a1a2e;color:#bbb;text-align:center;border-radius:8px;font-size:13px}
  .footer p{margin:4px 0}
</style>
</head>
<body>
  <div class="header">
    <h1>Welcome to ${escape(gymName)}, ${escape(member.name)}!</h1>
    <p>Your personalised fitness plan is ready — built specifically for your body and your goal.</p>
  </div>

  <p>Hi ${escape(member.name)},</p>
  <p>We have analysed your InBody report and created a complete plan tailored to your goal of <strong>${escape(member.primary_goal)}</strong>. Everything below is specific to your body composition, fitness history, and the number of days you can train.</p>

  <h2>Your Trainer Assessment</h2>
  <pre>${escape(assessment)}</pre>

  <h2>Your Weekly Workout Plan</h2>
  <pre>${escape(workout)}</pre>

  <h2>Your Nutrition Plan</h2>
  <pre>${escape(nutrition)}</pre>

  <div class="next-steps">
    <h2>Next Steps</h2>
    <ol>
      <li>Read through your assessment and share any questions with your trainer on Day 1.</li>
      <li>Read through your workout plan the evening before each training session.</li>
      <li>Meal prep your first week using the sample meal plan as a guide.</li>
      <li>Track your food in MyFitnessPal or Healthifyme to stay on your macro targets.</li>
      <li>Schedule your first training session if you have not done so already.</li>
    </ol>
  </div>

  <div class="footer">
    <p><strong>${escape(gymName)}</strong></p>
    <p>Questions? Reply to this email or speak to your trainer directly.</p>
    <p style="font-size:11px;color:#888;margin-top:8px">Auto-generated by Gym Onboarding AI</p>
  </div>
</body>
</html>`;
}

async function sendTrainerEmail(member, inbody, assessment, workout, nutrition) {
  console.log('[sendEmail] Sending trainer report email...');
  try {
    const auth = getGoogleAuth();
    const gmail = google.gmail({ version: 'v1', auth });

    const senderEmail = process.env.GMAIL_USER;

    const subject = `New Member — ${member.name} | ${member.primary_goal}`;
    const html = buildTrainerHtml(member, inbody, assessment, workout, nutrition);
    const raw = buildMimeMessage(process.env.TRAINER_EMAIL, senderEmail, subject, html);

    await gmail.users.messages.send({ userId: 'me', requestBody: { raw } });
    console.log(`[sendEmail] Trainer email sent to ${process.env.TRAINER_EMAIL}`);
  } catch (error) {
    console.error(`[sendEmail] Trainer email failed: ${error.message}`);
  }
}

async function sendClientEmail(member, assessment, workout, nutrition) {
  console.log('[sendEmail] Sending client welcome email...');
  try {
    const auth = getGoogleAuth();
    const gmail = google.gmail({ version: 'v1', auth });

    const gymName = process.env.GYM_NAME || 'Your Gym';
    const senderEmail = process.env.GMAIL_USER;

    const subject = `Welcome to ${gymName}, ${member.name} — Your Plan is Ready!`;
    const html = buildClientHtml(member, assessment, workout, nutrition, gymName);
    const raw = buildMimeMessage(member.email, senderEmail, subject, html);

    await gmail.users.messages.send({ userId: 'me', requestBody: { raw } });
    console.log(`[sendEmail] Client email sent to ${member.email}`);
  } catch (error) {
    console.error(`[sendEmail] Client email failed: ${error.message}`);
  }
}

module.exports = { sendTrainerEmail, sendClientEmail };
